#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
source "${SCRIPT_DIR}/env.sh"

log() {
  printf '[firemarshal-build] %s\n' "$*"
}

die() {
  printf '[firemarshal-build][error] %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  bash scripts/build-firemarshal-images.sh

Default:
  Clean, build, and install every FireMarshal workload JSON generated by
  scripts/package-firemarshal-workload.sh.

Inputs:
  $PYTORCH_CHIPYARD_WORKLOAD_DIR/*.json

Outputs:
  $FIREMARSHAL_IMAGE_DIR/<workload>/<workload>-bin
  $FIREMARSHAL_IMAGE_DIR/<workload>/<workload>.img
  $FIRESIM_WORKLOAD_DIR/<workload>.json

Notes:
  FireMarshal mounts rootfs images while applying overlays. This script assumes
  the user can run sudo and validates credentials with sudo -v before building.

Options:
  -h, --help  Show this help.
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument '$1'; pass --help for usage"
      ;;
  esac
done

[[ -f "${FIREMARSHAL_DIR}/marshal" ]] || \
  die "FireMarshal is not initialized at ${FIREMARSHAL_DIR}; check CHIPYARD_DIR or FIREMARSHAL_DIR"
[[ -d "${FIRESIM_DEPLOY_DIR}" ]] || \
  die "FireSim deploy directory not found: ${FIRESIM_DEPLOY_DIR}; check CHIPYARD_DIR or FIRESIM_DEPLOY_DIR"
[[ -d "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" ]] || \
  die "workload directory not found: ${PYTORCH_CHIPYARD_WORKLOAD_DIR}; run scripts/package-firemarshal-workload.sh first"

export TMPDIR="${TMPDIR:-$PYTORCH_CHIPYARD_FIREMARSHAL_TMP_DIR}"

mkdir -p \
  "${MARSHAL_MOUNT_DIR}" \
  "${LIBGUESTFS_CACHEDIR}" \
  "${LIBGUESTFS_TMPDIR}" \
  "${TMPDIR}" \
  "${FIRESIM_WORKLOAD_DIR}"

workload_jsons=()
while IFS= read -r -d '' workload_json; do
  workload_jsons+=("${workload_json}")
done < <(find "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" -maxdepth 1 -type f -name '*.json' ! -name '*base.json' -print0 | sort -z)

if [[ "${#workload_jsons[@]}" -eq 0 ]]; then
  die "no workload JSON files found under ${PYTORCH_CHIPYARD_WORKLOAD_DIR}; run scripts/package-firemarshal-workload.sh first"
fi

log "checking sudo credentials"
sudo -v

sudo_keepalive_pid=""
keep_sudo_alive() {
  while true; do
    sudo -n true >/dev/null 2>&1 || exit 0
    sleep 60
  done
}

cleanup() {
  if [[ -n "${sudo_keepalive_pid}" ]]; then
    kill "${sudo_keepalive_pid}" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

keep_sudo_alive &
sudo_keepalive_pid="$!"

log "FireMarshal dir: ${FIREMARSHAL_DIR}"
log "workload dir: ${PYTORCH_CHIPYARD_WORKLOAD_DIR}"
log "image dir: ${FIREMARSHAL_IMAGE_DIR}"
log "FireSim workload dir: ${FIRESIM_WORKLOAD_DIR}"
log "cleaning/building/installing ${#workload_jsons[@]} workload(s)"

(
  cd "${FIREMARSHAL_DIR}"
  ./marshal --workdir "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" clean "${workload_jsons[@]}"
  ./marshal --workdir "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" build "${workload_jsons[@]}"
  ./marshal --workdir "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" install "${workload_jsons[@]}"
)

log "done"
