#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
source "${SCRIPT_DIR}/env.sh"

log() {
  printf '[firesim-run] %s\n' "$*"
}

warn() {
  printf '[firesim-run][warn] %s\n' "$*" >&2
}

die() {
  printf '[firesim-run][error] %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  bash scripts/run-firesim-workloads.sh [options]

Default:
  Run every FireSim workload generated by scripts/package-firemarshal-workload.sh,
  then collect the latest model.log, autotune.log, and output.bin under
  scripts/figures/results-workload/<workload>/, and copy model/autotune logs to
  examples/.logs. For LLM workloads with sequence
  length greater than 256, output.bin is not collected because those workloads
  run with --no-output.

Options:
  --workload=NAME      Run/collect one workload. May be repeated or comma-separated.
  --resume             Keep collected results/logs and skip workloads that already
                       have collected outputs.
  --resume-from=NAME   Keep collected results/logs and start from NAME in the
                       selected/discovered workload order.
  --rvv-panic-retries=N|unlimited
                       Retry an RVV workload after a detected kernel panic or
                       corrupt UART. Default: unlimited; 0 disables retries.
  -h, --help           Show this help.

Environment:
  PYTORCH_CHIPYARD_FPGA_DB                  Default: /opt/firesim-db.json
  FIRESIM_RUNS_DIR                          Default: $WORKSPACE/FIRESIM_RUNS_DIR
  PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR      Generated config_runtime files.
  PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR     FireSim results-workload directory.
  PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR
                                             Collected result directory.
  PYTORCH_CHIPYARD_LOG_DIR                  Current stage2 log directory.
  PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_HOST    Default: localhost
  PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_SPEC    Default: one_fpgas_spec
  PYTORCH_CHIPYARD_CLEAN_FIRESIM_RUNS_DIR=0 Skip clearing FIRESIM_RUNS_DIR.
  PYTORCH_CHIPYARD_CLEAN_COLLECTED_RESULTS=0
                                             Skip clearing collected result/log dirs.
  PYTORCH_CHIPYARD_KEEP_RUNFARM=1           Skip terminaterunfarm.
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_OVERRIDES
                                             Comma-separated workload=hw_config list.

Failure handling:
  While runworkload is active, UART logs are monitored for guest failures such
  as kernel panics, oopses, signals, and FireSim failure markers. The active
  run is terminated immediately. RVV kernel failures are cleaned up with
  firesim kill and retried with a new run farm; other failures stop Stage 2.

Per-workload hardware override:
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_<WORKLOAD>

Example:
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_RESNET50_GEMMINI_4CORE=alveo_u250_firesim_fp8x8_gemmini_rocket_4core_no_nic \
    bash scripts/run-firesim-workloads.sh --workload=resnet50-gemmini-4core
EOF
}

validate_name() {
  local label="$1"
  local value="$2"
  [[ "${value}" =~ ^[A-Za-z0-9._-]+$ ]] || \
    die "invalid ${label} '${value}'; use only letters, numbers, '.', '_', and '-'"
}

require_file() {
  local path="$1"
  [[ -f "${path}" ]] || die "missing required file: ${path}"
}

require_dir() {
  local path="$1"
  [[ -d "${path}" ]] || die "missing required directory: ${path}"
}

clean_firesim_runs_dir() {
  local dir="${FIRESIM_RUNS_DIR}"
  local enabled="${PYTORCH_CHIPYARD_CLEAN_FIRESIM_RUNS_DIR:-1}"

  [[ "${enabled}" == "1" ]] || return 0
  [[ -n "${dir}" && "${dir}" != "/" ]] || die "refusing to clean unsafe FIRESIM_RUNS_DIR='${dir}'"
  mkdir -p "${dir}"
  find "${dir}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
  log "cleaned FIRESIM_RUNS_DIR: ${dir}"
}

clean_dir_contents() {
  local label="$1"
  local dir="$2"

  [[ -n "${dir}" && "${dir}" != "/" ]] || die "refusing to clean unsafe ${label}='${dir}'"
  mkdir -p "${dir}"
  find "${dir}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
  log "cleaned ${label}: ${dir}"
}

clean_collected_results() {
  local enabled="${PYTORCH_CHIPYARD_CLEAN_COLLECTED_RESULTS:-1}"

  if [[ "${RESUME_MODE:-0}" == "1" || -n "${RESUME_FROM:-}" ]]; then
    enabled=0
  fi

  if [[ "${enabled}" != "1" ]]; then
    mkdir -p "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}" "${PYTORCH_CHIPYARD_LOG_DIR}"
    log "kept collected result/log dirs for resume"
    return 0
  fi

  clean_dir_contents "PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR" "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}"
  clean_dir_contents "PYTORCH_CHIPYARD_LOG_DIR" "${PYTORCH_CHIPYARD_LOG_DIR}"
}

yaml_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

split_workload_arg() {
  local value="$1"
  local item
  local -a items

  IFS=, read -r -a items <<<"${value}"
  for item in "${items[@]}"; do
    [[ -n "${item}" ]] || continue
    validate_name "workload" "${item}"
    SELECTED_WORKLOADS+=("${item}")
  done
}

discover_workloads() {
  local json path base workload

  [[ -d "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" ]] || return 0
  while IFS= read -r path; do
    base="$(basename "${path}")"
    workload="${base%.json}"
    case "${workload}" in
      br-base | *base)
        continue
        ;;
    esac
    validate_name "workload" "${workload}"
    printf '%s\n' "${workload}"
  done < <(find "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" -maxdepth 1 -type f -name '*.json' -print | sort -V)
}

unique_workloads() {
  local -A seen=()
  local workload

  for workload in "$@"; do
    [[ -n "${seen[${workload}]:-}" ]] && continue
    seen["${workload}"]=1
    printf '%s\n' "${workload}"
  done
}

require_boom_flex_kernel_package() {
  local workload="$1"
  local runner image

  case "${workload}" in
    opt-boom-gemmini-flash-*tok-1core | opt-boom-gemmini-window-*tok-1core) ;;
    *) return 0 ;;
  esac

  runner="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/overlay-${workload}/root/llm/run_${workload}.sh"
  image="${FIREMARSHAL_IMAGE_DIR}/${workload}/${workload}.img"
  require_file "${runner}"
  grep -Fq -- '--kernel-only=flex_attention' "${runner}" || \
    die "${workload} was packaged for full-model execution; rerun Stage 2 without --resume-from/--resume to regenerate its ELF, package, and image"
  require_file "${image}"
  [[ "${image}" -nt "${runner}" ]] || \
    die "${workload} FireMarshal image predates its kernel-only runner; rebuild the image before FireSim execution"
}

load_workloads() {
  local workloads=()
  local workload

  if [[ "${#SELECTED_WORKLOADS[@]}" -gt 0 ]]; then
    mapfile -t workloads < <(unique_workloads "${SELECTED_WORKLOADS[@]}")
  else
    mapfile -t workloads < <(discover_workloads)
  fi

  [[ "${#workloads[@]}" -gt 0 ]] || \
    die "no packaged workloads found under ${PYTORCH_CHIPYARD_WORKLOAD_DIR}; run scripts/package-firemarshal-workload.sh first"

  for workload in "${workloads[@]}"; do
    require_file "${PYTORCH_CHIPYARD_WORKLOAD_DIR}/${workload}.json"
    require_file "${FIRESIM_WORKLOAD_DIR}/${workload}.json"
    require_boom_flex_kernel_package "${workload}"
  done

  WORKLOADS=("${workloads[@]}")
}

apply_resume_filters() {
  local workload
  local found=0
  local filtered=()
  local pending=()

  if [[ -n "${RESUME_FROM}" ]]; then
    for workload in "${WORKLOADS[@]}"; do
      if [[ "${workload}" == "${RESUME_FROM}" ]]; then
        found=1
      fi
      if [[ "${found}" -eq 1 ]]; then
        filtered+=("${workload}")
      fi
    done

    [[ "${found}" -eq 1 ]] || \
      die "resume workload '${RESUME_FROM}' was not found in the selected/discovered workload list"

    WORKLOADS=("${filtered[@]}")
    log "resume-from ${RESUME_FROM}: ${#WORKLOADS[@]} workload(s) remaining"
  fi

  if [[ "${RESUME_MODE}" -eq 1 ]]; then
    for workload in "${WORKLOADS[@]}"; do
      if collected_result_complete "${workload}"; then
        log "resume: skipping completed workload ${workload}"
      else
        pending+=("${workload}")
      fi
    done

    WORKLOADS=("${pending[@]}")
    if [[ "${#WORKLOADS[@]}" -eq 0 ]]; then
      log "resume: no pending workloads"
      exit 0
    fi
    log "resume: ${#WORKLOADS[@]} pending workload(s)"
  fi
}

core_for_workload() {
  local workload="$1"

  if [[ "${workload}" =~ (^|-)([0-9]+)core($|-) ]]; then
    printf '%s\n' "${BASH_REMATCH[2]}"
    return 0
  fi

  return 1
}

is_llm_workload() {
  local workload="$1"

  case "${workload}" in
    gpt2-* | gpt-neo-* | opt-* | pythia-* | *tok*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

llm_seq_len_for_workload() {
  local workload="$1"

  if [[ "${workload}" =~ (^|-)([0-9]+)tok($|-) ]]; then
    printf '%s\n' "${BASH_REMATCH[2]}"
  else
    printf '%s\n' 256
  fi
}

should_collect_output_bin() {
  local workload="$1"
  local seq_len

  case "${workload}" in
    opt-boom-gemmini-flash-*tok-1core | opt-boom-gemmini-window-*tok-1core)
      return 1
      ;;
  esac

  if is_llm_workload "${workload}"; then
    seq_len="$(llm_seq_len_for_workload "${workload}")"
    [[ "${seq_len}" -le 256 ]]
    return
  fi

  return 0
}

collected_result_dir() {
  local workload="$1"

  printf '%s/%s\n' "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}" "${workload}"
}

collected_result_complete() {
  local workload="$1"
  local dest

  dest="$(collected_result_dir "${workload}")"
  [[ -d "${dest}" ]] || return 1

  [[ -f "${dest}/.completed" ]] || return 1
  [[ -s "${dest}/model.log" ]] || return 1
  [[ -s "${dest}/autotune.log" ]] || return 1
  if should_collect_output_bin "${workload}"; then
    [[ -s "${dest}/output.bin" ]] || return 1
  fi
  if [[ -f "${dest}/run.log" ]]; then
    grep -Fq '[runner] model_ret=0' "${dest}/run.log" || return 1
  fi
}

contains_tag() {
  local workload="$1"
  local tag="$2"

  case "-${workload}-" in
    *-"${tag}"-*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

env_suffix_for_workload() {
  local workload="$1"
  local suffix

  suffix="${workload^^}"
  suffix="${suffix//[^A-Z0-9_]/_}"
  printf '%s\n' "${suffix}"
}

override_hw_config_for() {
  local workload="$1"
  local suffix var_name overrides pair key value

  suffix="$(env_suffix_for_workload "${workload}")"
  var_name="PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_${suffix}"
  if [[ -n "${!var_name:-}" ]]; then
    printf '%s\n' "${!var_name}"
    return 0
  fi

  overrides="${PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_OVERRIDES:-}"
  [[ -n "${overrides}" ]] || return 1

  IFS=, read -r -a pairs <<<"${overrides}"
  for pair in "${pairs[@]}"; do
    key="${pair%%=*}"
    value="${pair#*=}"
    [[ "${key}" == "${workload}" && "${value}" != "${pair}" && -n "${value}" ]] || continue
    printf '%s\n' "${value}"
    return 0
  done

  return 1
}

infer_hw_config() {
  local workload="$1"
  local core

  if override_hw_config_for "${workload}"; then
    return 0
  fi

  core="$(core_for_workload "${workload}")" || \
    die "could not infer core count from workload '${workload}'"

  if contains_tag "${workload}" "boom"; then
    case "${core}" in
      1) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_1core_no_nic" ;;
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_4core_no_nic" ;;
      *) die "no BOOM hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "gemmini"; then
    case "${core}" in
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_4core_no_nic" ;;
      *) die "no Gemmini hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "rvv"; then
    case "${core}" in
      1) printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_4core_no_nic" ;;
      2) printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_2core_no_nic" ;;
      4)
        # Every four-thread RVV workload uses the same eight-hart target.
        # Harts 4-7 stay free, avoiding the kernel/OpenMP contention observed
        # when all four harts of the otherwise identical target are occupied.
        printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_8core_no_nic_30mhz"
        ;;
      *) die "no RVV hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "rocket"; then
    printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic"
  elif contains_tag "${workload}" "scalar"; then
    printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic"
  elif is_llm_workload "${workload}"; then
    case "${core}" in
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic" ;;
      *) die "no LLM fallback hardware config mapping for ${workload}" ;;
    esac
  elif [[ "${core}" == "16" ]]; then
    printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic"
  else
    die "could not infer hardware config for workload '${workload}'; set PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_$(env_suffix_for_workload "${workload}")"
  fi
}

require_hw_config() {
  local hw_config="$1"

  require_file "${FIRESIM_HWDB_PATH}"
  require_file "${FIRESIM_BUILD_RECIPES_PATH}"

  if ! grep -q "^${hw_config}:" "${FIRESIM_HWDB_PATH}"; then
    die "hardware config '${hw_config}' not found in ${FIRESIM_HWDB_PATH}"
  fi
}

generate_runtime_config() {
  local workload="$1"
  local hw_config="$2"
  local fpga_db="$3"
  local runtime="${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}/config_runtime_${workload}.yaml"

  mkdir -p "${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}" "${FIRESIM_RUNS_DIR}"

  cat >"${runtime}" <<EOF
# Auto-generated by scripts/run-firesim-workloads.sh

run_farm:
  base_recipe: run-farm-recipes/externally_provisioned.yaml
  recipe_arg_overrides:
    default_platform: XilinxAlveoU250InstanceDeployManager
    default_simulation_dir: $(yaml_quote "${FIRESIM_RUNS_DIR}")
    default_fpga_db: $(yaml_quote "${fpga_db}")
    run_farm_hosts_to_use:
        - $(yaml_quote "${PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_HOST}"): ${PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_SPEC}

metasimulation:
  metasimulation_enabled: false
  metasimulation_host_simulator: verilator
  metasimulation_only_plusargs: "+fesvr-step-size=128 +max-cycles=100000000"
  metasimulation_only_vcs_plusargs: "+vcs+initreg+0 +vcs+initmem+0"

target_config:
    topology: no_net_config
    no_net_num_nodes: 1
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1
    default_hw_config: ${hw_config}
    plusarg_passthrough: ""

tracing:
    enable: no
    output_format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read_rate: 0

workload:
    workload_name: ${workload}.json
    terminate_on_completion: yes
    suffix_tag: ${workload}

host_debug:
    zero_out_dram: no
    disable_synth_asserts: no

synth_print:
    start: 0
    end: -1
    cycle_prefix: yes
EOF

  printf '%s\n' "${runtime}"
}

latest_result_dir() {
  local workload="$1"
  local marker="${2:-}"
  local newer_args=()

  [[ -d "${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}" ]] || return 1
  if [[ -n "${marker}" ]]; then
    newer_args=(-newer "${marker}")
  fi

  find "${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}" \
    -maxdepth 2 \
    -type d \
    -name "${workload}0" \
    "${newer_args[@]}" \
    -printf '%T@ %p\n' 2>/dev/null | \
    sort -nr | \
    head -n 1 | \
    cut -d' ' -f2-
}

copy_if_present() {
  local src="$1"
  local dst="$2"

  if [[ -f "${src}" ]]; then
    cp -f "${src}" "${dst}"
    return 0
  fi

  return 1
}

uart_has_repeated_corruption() {
  local uart="$1"

  # A failed target can emit an unbounded stream of 0xff/0x01 instead of a
  # printable panic. Normal boot UART output does not contain runs this long.
  tail -c 65536 "${uart}" 2>/dev/null | \
    od -An -v -tu1 | \
    awk '
      BEGIN { previous = -1; repeated = 0; found = 0 }
      {
        for (i = 1; i <= NF; i++) {
          byte = $i
          if (byte == previous) {
            repeated++
          } else {
            previous = byte
            repeated = 1
          }
          if ((byte == 1 || byte == 255) && repeated >= 4096) {
            found = 1
          }
        }
      }
      END { exit(found ? 0 : 1) }
    '
}

uart_failure_line() {
  local uart line
  local pattern='\*\*\* FAILED \*\*\*|Kernel panic|Oops -|Unhandled fault|unhandled signal|Unable to handle kernel|BUG: unable to handle|Segmentation fault|Illegal instruction|Assertion failed'

  [[ -d "${FIRESIM_RUNS_DIR}" ]] || return 1
  while IFS= read -r -d '' uart; do
    if uart_has_repeated_corruption "${uart}"; then
      printf '%s: at least 4096 repeated 0xff/0x01 bytes in UART output\n' "${uart}"
      return 0
    fi

    line="$(tail -c 1048576 "${uart}" 2>/dev/null | LC_ALL=C strings | grep -E -m1 "${pattern}" || true)"
    if [[ -n "${line}" ]]; then
      printf '%s: %s\n' "${uart}" "${line}"
      return 0
    fi
  done < <(find "${FIRESIM_RUNS_DIR}" -maxdepth 2 -type f -name uartlog -print0 2>/dev/null)

  return 1
}

uart_kernel_failure_line() {
  local uart line
  local pattern='Kernel panic|Oops -|Unable to handle kernel|BUG: unable to handle|Fatal exception in interrupt'

  [[ -d "${FIRESIM_RUNS_DIR}" ]] || return 1
  while IFS= read -r -d '' uart; do
    if uart_has_repeated_corruption "${uart}"; then
      printf '%s: at least 4096 repeated 0xff/0x01 bytes in UART output\n' "${uart}"
      return 0
    fi

    line="$(tail -c 1048576 "${uart}" 2>/dev/null | LC_ALL=C strings | grep -E -m1 "${pattern}" || true)"
    if [[ -n "${line}" ]]; then
      printf '%s: %s\n' "${uart}" "${line}"
      return 0
    fi
  done < <(find "${FIRESIM_RUNS_DIR}" -maxdepth 2 -type f -name uartlog -print0 2>/dev/null)

  return 1
}

failure_text_is_retryable_kernel() {
  local failure="$1"

  case "${failure}" in
    *'Kernel panic'* | *'Oops -'* | *'Unable to handle kernel'* | \
      *'BUG: unable to handle'* | *'Fatal exception in interrupt'* | \
      *'repeated 0xff/0x01 bytes'*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

terminate_process_group() {
  local pid="$1"
  local attempt

  kill -TERM -- "-${pid}" 2>/dev/null || kill -TERM "${pid}" 2>/dev/null || true
  for attempt in {1..10}; do
    kill -0 "${pid}" 2>/dev/null || return 0
    sleep 1
  done
  kill -KILL -- "-${pid}" 2>/dev/null || kill -KILL "${pid}" 2>/dev/null || true
}

run_firesim_workload_monitored() {
  local workload="$1"
  local runtime="$2"
  local pid manager_status=0 failure=""

  setsid firesim runworkload \
    -c "${runtime}" \
    -a "${FIRESIM_HWDB_PATH}" \
    -r "${FIRESIM_BUILD_RECIPES_PATH}" &
  pid=$!

  while kill -0 "${pid}" 2>/dev/null; do
    if failure="$(uart_kernel_failure_line)"; then
      warn "${workload}: detected retryable guest kernel failure: ${failure}"
      terminate_process_group "${pid}"
      wait "${pid}" 2>/dev/null || true
      return 70
    fi
    if failure="$(uart_failure_line)"; then
      if failure_text_is_retryable_kernel "${failure}"; then
        warn "${workload}: detected retryable guest kernel failure: ${failure}"
        terminate_process_group "${pid}"
        wait "${pid}" 2>/dev/null || true
        return 70
      fi
      warn "${workload}: detected non-retryable guest failure: ${failure}"
      terminate_process_group "${pid}"
      wait "${pid}" 2>/dev/null || true
      return 71
    fi
    sleep 5
  done

  wait "${pid}" || manager_status=$?

  if failure="$(uart_kernel_failure_line)"; then
    warn "${workload}: detected retryable guest kernel failure: ${failure}"
    return 70
  fi
  if failure="$(uart_failure_line)"; then
    if failure_text_is_retryable_kernel "${failure}"; then
      warn "${workload}: detected retryable guest kernel failure: ${failure}"
      return 70
    fi
    warn "${workload}: detected non-retryable guest failure: ${failure}"
    return 71
  fi

  return "${manager_status}"
}

archive_failed_attempt() {
  local workload="$1"
  local attempt="$2"
  local marker="$3"
  local dest result_dir uart slot

  dest="${PYTORCH_CHIPYARD_LOG_DIR}/failed-attempts/${workload}/attempt-${attempt}"
  mkdir -p "${dest}"

  result_dir="$(latest_result_dir "${workload}" "${marker}")"
  if [[ -n "${result_dir}" ]]; then
    copy_if_present "${result_dir}/run.log" "${dest}/run.log" || true
    if [[ -f "${result_dir}/uartlog" ]]; then
      tail -c 4194304 "${result_dir}/uartlog" >"${dest}/uartlog.tail"
    fi
  fi

  while IFS= read -r -d '' uart; do
    slot="$(basename "$(dirname "${uart}")")"
    tail -c 4194304 "${uart}" >"${dest}/${slot}-uartlog.tail"
  done < <(find "${FIRESIM_RUNS_DIR}" -maxdepth 2 -type f -name uartlog -print0 2>/dev/null)

  log "${workload}: archived failed attempt ${attempt} -> ${dest}"
}

validate_workload_result() {
  local workload="$1"
  local result_dir="$2"
  local uart="${result_dir}/uartlog"
  local run_log="${result_dir}/run.log"
  local failure=""

  [[ -f "${uart}" ]] || {
    warn "${workload}: missing uartlog in ${result_dir}"
    return 1
  }
  if uart_has_repeated_corruption "${uart}"; then
    warn "${workload}: repeated 0xff/0x01 bytes indicate corrupt UART output in ${uart}"
    return 70
  fi
  failure="$(tail -c 1048576 "${uart}" 2>/dev/null | LC_ALL=C strings | \
    grep -E -m1 'Kernel panic|Oops -|Unable to handle kernel|BUG: unable to handle|Fatal exception in interrupt' || true)"
  if [[ -n "${failure}" ]]; then
    warn "${workload}: retryable kernel failure found in ${uart}: ${failure}"
    return 70
  fi
  if LC_ALL=C grep -aEq '\*\*\* FAILED \*\*\*|Kernel panic|Oops -|Unhandled fault|unhandled signal|Unable to handle kernel|BUG: unable to handle|Segmentation fault|Illegal instruction|Assertion failed' "${uart}"; then
    warn "${workload}: failure marker found in ${uart}"
    return 1
  fi
  LC_ALL=C grep -aFq '*** PASSED ***' "${uart}" || {
    warn "${workload}: FireSim PASS marker not found in ${uart}"
    return 1
  }
  [[ -s "${run_log}" ]] || {
    warn "${workload}: missing or empty run.log in ${result_dir}"
    return 1
  }
  grep -Fq '[runner] model_ret=0' "${run_log}" || {
    warn "${workload}: model did not return zero according to ${run_log}"
    return 1
  }
  [[ -s "${result_dir}/model.log" ]] || {
    warn "${workload}: missing or empty model.log in ${result_dir}"
    return 1
  }
  [[ -s "${result_dir}/autotune.log" ]] || {
    warn "${workload}: missing or empty autotune.log in ${result_dir}"
    return 1
  }
  if should_collect_output_bin "${workload}"; then
    [[ -s "${result_dir}/output.bin" ]] || {
      warn "${workload}: missing or empty output.bin in ${result_dir}"
      return 1
    }
  fi
}

collect_workload_result() {
  local workload="$1"
  local marker="${2:-}"
  local result_dir dest log_dest copied=0 validation_status=0

  result_dir="$(latest_result_dir "${workload}" "${marker}")"
  if [[ -z "${result_dir}" ]]; then
    warn "${workload}: no result directory found under ${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}"
    return 1
  fi

  validate_workload_result "${workload}" "${result_dir}" || validation_status=$?
  [[ "${validation_status}" -eq 0 ]] || return "${validation_status}"

  dest="$(collected_result_dir "${workload}")"
  log_dest="${PYTORCH_CHIPYARD_LOG_DIR}"
  mkdir -p "${dest}" "${log_dest}"

  copy_if_present "${result_dir}/run.log" "${dest}/run.log" || true
  copy_if_present "${result_dir}/uartlog" "${dest}/uartlog" || true

  if copy_if_present "${result_dir}/model.log" "${dest}/model.log"; then
    cp -f "${result_dir}/model.log" "${log_dest}/${workload}-model.log"
    copied=1
  else
    warn "${workload}: missing model.log in ${result_dir}"
  fi

  if copy_if_present "${result_dir}/autotune.log" "${dest}/autotune.log"; then
    cp -f "${result_dir}/autotune.log" "${log_dest}/${workload}-autotune.log"
    copied=1
  else
    warn "${workload}: missing autotune.log in ${result_dir}"
  fi

  if should_collect_output_bin "${workload}"; then
    if copy_if_present "${result_dir}/output.bin" "${dest}/output.bin"; then
      copied=1
    else
      warn "${workload}: missing output.bin in ${result_dir}"
    fi
  else
    rm -f "${dest}/output.bin"
    log "${workload}: skipped output.bin collection for no-output workload"
  fi

  [[ "${copied}" -eq 1 ]] || return 1

  log "${workload}: collected results from ${result_dir} -> ${dest}"
  log "${workload}: collected logs -> ${log_dest}"
}

run_workload() {
  local workload="$1"
  local hw_config="$2"
  local runtime="$3"
  local marker="$4"
  local status=0
  local collect_status=0
  local runworkload_started=0
  local keep_runfarm="${PYTORCH_CHIPYARD_KEEP_RUNFARM:-${KEEP_RUNFARM:-0}}"

  log "${workload}: launchrunfarm/infrasetup/runworkload with ${hw_config}"

  (
    set -euo pipefail
    cd "${FIRESIM_DIR}"
    set +u
    source ./sourceme-manager.sh --skip-ssh-setup
    set -u

    firesim launchrunfarm -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || status=$?

    if [[ "${status}" -eq 0 ]]; then
      firesim infrasetup -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || status=$?
    fi

    if [[ "${status}" -eq 0 ]]; then
      runworkload_started=1
      run_firesim_workload_monitored "${workload}" "${runtime}" || status=$?
    fi

    collect_workload_result "${workload}" "${marker}" || collect_status=$?
    if [[ "${status}" -eq 0 && "${collect_status}" -ne 0 ]]; then
      status="${collect_status}"
    fi

    if [[ "${status}" -ne 0 && "${runworkload_started}" -eq 1 ]]; then
      log "${workload}: cleaning failed FireSim runtime"
      firesim kill -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || \
        warn "${workload}: firesim kill failed; continuing cleanup"
    fi

    if [[ "${keep_runfarm}" != "1" ]]; then
      firesim terminaterunfarm -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" --forceterminate || true
    fi

    exit "${status}"
  ) || status=$?

  if [[ "${status}" -eq 0 ]]; then
    touch "$(collected_result_dir "${workload}")/.completed"
  fi
  return "${status}"
}

SELECTED_WORKLOADS=()
RESUME_MODE=0
RESUME_FROM=""
RVV_PANIC_RETRIES=unlimited

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --workload)
      [[ "$#" -ge 2 ]] || die "--workload requires a value"
      split_workload_arg "$2"
      shift 2
      ;;
    --workload=*)
      split_workload_arg "${1#--workload=}"
      shift
      ;;
    --resume)
      RESUME_MODE=1
      shift
      ;;
    --resume-from)
      [[ "$#" -ge 2 ]] || die "--resume-from requires a value"
      validate_name "workload" "$2"
      RESUME_FROM="$2"
      shift 2
      ;;
    --resume-from=*)
      RESUME_FROM="${1#--resume-from=}"
      validate_name "workload" "${RESUME_FROM}"
      shift
      ;;
    --rvv-panic-retries)
      [[ "$#" -ge 2 ]] || die "--rvv-panic-retries requires a value"
      RVV_PANIC_RETRIES="$2"
      shift 2
      ;;
    --rvv-panic-retries=*)
      RVV_PANIC_RETRIES="${1#--rvv-panic-retries=}"
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument '$1'; pass --help for usage"
      ;;
  esac
done

[[ "${RVV_PANIC_RETRIES}" == "unlimited" || "${RVV_PANIC_RETRIES}" =~ ^[0-9]+$ ]] || \
  die "invalid --rvv-panic-retries=${RVV_PANIC_RETRIES}; expected a non-negative integer or unlimited"

require_dir "${FIRESIM_DIR}"
require_dir "${FIRESIM_WORKLOAD_DIR}"

WORKLOADS=()
load_workloads
apply_resume_filters
clean_collected_results

require_file "${FIRESIM_DIR}/sourceme-manager.sh"
fpga_db="${PYTORCH_CHIPYARD_FPGA_DB}"
require_file "${fpga_db}"
log "FPGA DB: ${fpga_db}"

for workload in "${WORKLOADS[@]}"; do
  hw_config="$(infer_hw_config "${workload}")"
  require_hw_config "${hw_config}"
  runtime="$(generate_runtime_config "${workload}" "${hw_config}" "${fpga_db}")"
  marker="${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}/.${workload}.run-start"
  mkdir -p "$(dirname "${marker}")"
  rm -f "$(collected_result_dir "${workload}")/.completed"
  attempt=1
  while true; do
    clean_firesim_runs_dir
    : >"${marker}"
    if run_workload "${workload}" "${hw_config}" "${runtime}" "${marker}"; then
      break
    else
      status=$?
    fi
    archive_failed_attempt "${workload}" "${attempt}" "${marker}"
    if contains_tag "${workload}" "rvv" && [[ "${status}" -eq 70 ]]; then
      if [[ "${RVV_PANIC_RETRIES}" == "unlimited" || \
          "${attempt}" -le "${RVV_PANIC_RETRIES}" ]]; then
        log "${workload}: retrying after kernel failure (${attempt}/${RVV_PANIC_RETRIES})"
        attempt=$((attempt + 1))
        continue
      fi
    fi
    die "${workload}: failed with status ${status}; stopping before the next workload infrasetup"
  done
done
